### ISSUE TITLE
make sure Respond components work for all kinds of functions

### ISSUE THREAD

**Issue by faceyspacey** [faceyspacey/remixx#7]
- arrow
- regular 
- others??

**Comment by ScriptedAlchemy** [comment]
Yep, needs to work for `function Test`, `Test = function`, `const ()=>`,

**Comment by faceyspacey** [comment]
this should be one and done and just outa the way. its the same code u got, but for different visitor methods

**Comment by ScriptedAlchemy** [comment]
Yep pretty much
